os: linux
dist: focal

language: node_js

node_js:
  - 'node'

install:
  - npm install -g codecov

script:
  - yarn --frozen-lockfile
  - yarn build
  - codecov

cache:
  npm: true
  yarn: true
  directories:
    - node_modules