os: linux
dist: focal

language: node_js

node_js:
  - 'node'

deploy:
  provider: pages:git
  edge: true
  token: ${GH_TOKEN}
  on:
    branch: pages:git

cache:
  yarn: true
  directories:
    - .cache
    - node_modules
    - public
