os: linux
dist: focal

language: node_js

node_js:
  - 'node'

install:
  - npm install -g codecov

script:
  - npm install --package-lock-only
  - npm run build
  - codecov

cache:
  npm: true
  yarn: true
  directories:
    - .cache
    - node_modules
    - public
