os: linux
dist: focal

language: node_js

node_js:
  - 'node'

before_script:
  - npm install -g gatsby-cli

deploy:
  provider: pages:git
  name: ${GH_USERNAME}
  email: ${GH_EMAIL}
  token: ${GH_TOKEN}
  edge:
    edge: true
    cleanup: true

cache:
  npm: true
  yarn: true
  directories:
    - node_modules
    - public
    - .cache