version: 2.1

orbs:
    node: circleci/node@4.7

workflows:
    example-workflow:
      jobs:
        - node/run:
            pkg-manager: yarn 
            yarn-run: build
            override-ci-command: yarn install --frozen-lockfile