version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - node/install:
          install-npm: true 
          install-yarn: true 
          lts: true 
          node-version: '14.17.6' 
          yarn-version: '1.22.5' 

workflows:
  build_ci:
    jobs:
      - build