version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  install:
    docker:
      - image: cimg/base:stable
    steps:
      - node/install-packages:
          pkg-manager: yarn 

workflows:
  install-workflow:
    jobs:
      - install
