version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  example-job:
    docker:
      - image: node:14.18-buster
    steps:
      - node/install-packages:
          pkg-manager: yarn 
          with-cache: true

workflows:
  example-workflow:
    jobs:
      - example-job