export { default as Head } from './head'
export { default as Layout } from './layout'
export { default as Loader } from './loader'
// export { default as Menu } from './menu'
export { default as Nav } from './nav'
export { default as Projects } from './sections/projects'
export { default as Jobs } from './sections/jobs'
